version: "3.9"

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    hostname: metabase
    volumes:
      - ./metabase-data:/metabase-data
      - ./plugins:/plugins
    ports:
      - 3000:3000
    environment:
      METABASE_SKIP_INITIAL_SETUP: 1
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: admin
      MB_DB_HOST: metabase-db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres
    container_name: metabase-db
    hostname: metabase-db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: admin
