name: tcc-project

include: 
  - ./airbyte/docker-compose.yaml
  - ./metabase/docker-compose.yaml

services:
  minio:
    image: quay.io/minio/minio 
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data 
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin_1_
    command: server /data --console-address ":9001"

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports: 
      - 8123:8123
      - 9002:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/config:/etc/clickhouse-server/config.d/*.xml
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=B3_DW
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=admin
