version: "3.1"
services:
  postgres:
    container_name: airflow-db
  scheduler:
    container_name: airflow-scheduler
  triggerer:
    container_name: airflow-triggerer
  webserver:
    container_name: airflow-webserver
